"""initial schema

Revision ID: 5778baf41658
Revises: 
Create Date: 2026-06-10 13:47:04.397689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5778baf41658'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assignment_status', sa.Enum('ACTIVE', 'DONE', name='servicetype'), nullable=False),
    sa.Column('git_weight', sa.Float(), nullable=True),
    sa.Column('doc_weight', sa.Float(), nullable=True),
    sa.Column('transcript_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'INSTRUCTOR', name='roletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contribution_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('final_calculated_scores', sa.JSON(), nullable=True),
    sa.Column('html_detailed_summary_report', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['project_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['project_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_workspace_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('GITHUB_REPOSITORY', 'GOOGLE_DRIVE_DOC', name='assettype'), nullable=False),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('connection_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['project_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_oauth_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('GITHUB', 'GOOGLE_DOCS', name='platformtype'), nullable=False),
    sa.Column('oauth_token', sa.String(), nullable=True),
    sa.Column('authorized_email', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('uploaded_by_student_id', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('ai_generated_summary', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('speaking_turns', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['project_groups.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_metrics_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('commit_frequency', sa.Integer(), nullable=False),
    sa.Column('lines_of_code_changed', sa.Integer(), nullable=False),
    sa.Column('pr_acceptance_rate', sa.Float(), nullable=False),
    sa.Column('issue_resolution_count', sa.Integer(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('revision_depth', sa.Integer(), nullable=False),
    sa.Column('comment_threads_count', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['shared_workspace_assets.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_metrics_log')
    op.drop_table('transcripts')
    op.drop_table('student_oauth_tokens')
    op.drop_table('shared_workspace_assets')
    op.drop_table('group_memberships')
    op.drop_table('contribution_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('project_groups')
    # ### end Alembic commands ###
