"""groups: owner, membership role, invitations

Revision ID: eeb96686ef1f
Revises: af18cc3f5164
Create Date: 2026-06-10 21:14:09.468019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb96686ef1f'
down_revision: Union[str, Sequence[str], None] = 'af18cc3f5164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'INSTRUCTOR', name='groupmemberrole'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['project_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_invitations_token_hash'), 'group_invitations', ['token_hash'], unique=True)
    op.add_column('group_memberships', sa.Column('role', sa.Enum('STUDENT', 'INSTRUCTOR', name='groupmemberrole'), nullable=False))
    op.create_unique_constraint('uq_group_user', 'group_memberships', ['group_id', 'user_id'])
    op.add_column('project_groups', sa.Column('owner_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'project_groups', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_groups', type_='foreignkey')
    op.drop_column('project_groups', 'owner_id')
    op.drop_constraint('uq_group_user', 'group_memberships', type_='unique')
    op.drop_column('group_memberships', 'role')
    op.drop_index(op.f('ix_group_invitations_token_hash'), table_name='group_invitations')
    op.drop_table('group_invitations')
    # ### end Alembic commands ###
